logging:
  level:
    root: INFO
    com.klikcair.service.demo: INFO
  file:
    name: /var/log/boot_demo/demo_service.log
  pattern:
    console: "%-6level [%d{yyyy-MM-dd HH:mm:ss.SSS,UTC}] [%t] %logger: %X{code} %msg %n"
    file: "%-6level [%d{yyyy-MM-dd HH:mm:ss.SSS,UTC}] [%t] %logger: %X{code} %msg %n"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      total-size-cap: 500MB
      max-history: 360
server:
  servlet:
    context-path: /api
    application-display-name: Demo application
  port: 9000
  error.whitelabel.enabled: false
management:
  port: 9001
  security:
    enabled: false
spring:
  mvc.throw-exception-if-no-handler-found: true
  resources.add-mappings: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_book
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
app:
  security:
    jwt:
      keystore-path: keys/keystore.jceks
      keystore-password: password
      key-alias: jwtsigning
      private-key-passphrase: password
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      timeout: 1000
    permits:
      - /v1/users/login
      - /v1/users/signup
